macro(evaluate_os)
	if(WIN32 OR MSVC)
		set(OS_WINDOWS 1)
	elseif(APPLE)
		set(OS_MAC 1)
	elseif(UNIX AND NOT APPLE)
		set(OS_LINUX 1)
	else()
		message(FATAL_ERROR "Unexpected OS: ${CMAKE_SYSTEM_NAME}!")
	endif()
endmacro(evaluate_os)